easyconfigs:
  - GCC-13.2.0.eb
  - foss-2023b.eb
  - intel-2023b.eb
  - SciPy-bundle-2023.11-gfbf-2023b.eb
  - h5py-3.11.0-foss-2023b.eb
  - CUDA-12.4.0.eb
  - Go-1.22.1.eb
  - NCCL-2.20.5-GCCcore-13.2.0-CUDA-12.4.0.eb
  - cuDNN-8.9.7.29-CUDA-12.4.0.eb
  - magma-2.7.2-foss-2023b-CUDA-12.4.0.eb
  - UCX-CUDA-1.15.0-GCCcore-13.2.0-CUDA-12.4.0.eb
  - TurboVNC-3.1.3-GCCcore-13.2.0.eb
  - VirtualGL-3.1.1-GCC-13.2.0.eb
  - Boost-1.83.0-GCC-13.2.0.eb
  - Boost.MPI-1.83.0-gompi-2023b.eb
  - R-4.4.1-gfbf-2023b.eb
  - R-bundle-CRAN-2024.06-foss-2023b.eb
  - RStudio-Server-2024.09.0+375-foss-2023b-Java-11-R-4.4.1.eb
  - JupyterLab-4.2.0-GCCcore-13.2.0.eb
  - JupyterNotebook-7.2.0-GCCcore-13.2.0.eb
  - jupyter-resource-usage-1.0.2-GCCcore-13.2.0.eb
  - nbclassic-1.0.0-GCCcore-13.2.0.eb
  - code-server-4.90.2.eb
  - Julia-1.10.4-linux-x86_64.eb
  - scikit-learn-1.4.0-gfbf-2023b.eb
  - BBMap-39.01-GCC-12.2.0.eb:
      options:
        try-toolchain-version: '13.2.0'
        experimental:
        try-update-deps:
        copy-ec:
  - BBMap-39.01-GCC-13.2.0.eb:
  - BLAST+-2.14.1-gompi-2023a.eb:
      options:
        try-toolchain-version: '2023b'
        experimental:
        try-update-deps:
        copy-ec:
  - BLAST+-2.14.1-gompi-2023b.eb:
  - BamTools-2.5.2-GCC-12.3.0.eb:
      options:
        try-toolchain-version: '13.2.0'
        experimental:
        try-update-deps:
        copy-ec:
  - BamTools-2.5.2-GCC-13.2.0.eb:
  - DendroPy-4.6.1-GCCcore-12.3.0.eb:
      options:
        try-toolchain-version: '13.2.0'
        experimental:
        try-update-deps:
        copy-ec:
  - DendroPy-4.6.1-GCCcore-13.2.0.eb:
  - lpsolve-5.5.2.11-GCC-12.2.0.eb:
      options:
        try-toolchain-version: '13.2.0'
        experimental:
        try-update-deps:
        copy-ec:
  - lpsolve-5.5.2.11-GCC-13.2.0.eb:
  - AUGUSTUS-3.5.0-foss-2023b.eb:
  - MetaEuk-7-GCC-13.2.0.eb:
  - miniprot-0.13-GCCcore-12.3.0.eb:
      options:
        try-toolchain-version: '13.2.0'
        try-software-version: '0.14'
        experimental:
        try-update-deps:
        copy-ec:
  - miniprot-0.14-GCCcore-13.2.0.eb:
      options:
        inject-checksums: 'sha256'
  - miniprot-0.14-GCCcore-13.2.0.eb:
  - prodigal-2.6.3-GCCcore-12.3.0.eb:
      options:
        try-toolchain-version: '13.2.0'
        experimental:
        try-update-deps:
        copy-ec:
  - prodigal-2.6.3-GCCcore-13.2.0.eb:
  - SEPP-4.5.5-foss-2023b.eb:
  - BUSCO-5.8.3-foss-2023b.eb:

